# Generated by Django 3.2.7 on 2021-11-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211105_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='class_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
