# Generated by Django 3.2.7 on 2021-11-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='classroom',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Класс обучения'),
        ),
        migrations.AlterField(
            model_name='item',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Предмет'),
        ),
    ]
